import styles from "./button.module.css";
/* styles is an object that contains mappings of CSS classnames to their 
corresponding unique identifers generated by CSS modules.*/

function Button({ type, children = "Button" }) {
  return (
    <button
      className={`${styles.button} ${type ? styles[`button--${type}`] : ""}`}
    >
      {children}
    </button>
  );
}

export default Button;
